import * as T from 'three';
import test from 'node:test';import assert from 'node:assert/strict';import {Elevator,FamilyControl,FLOORS,LIFT,cutLiftFloor,shaftContains} from './house-mobility.mjs';import {createWorld} from './world.mjs';import {canMove,moveBicycle,movePlayer} from './navigation.mjs';
createWorld();
test('五位家人切换保存各自位置，非法角色不改变控制权',()=>{const f=new FamilyControl(Array.from({length:5},(_,i)=>({position:{x:i,y:0,z:19}})));for(let i=1;i<5;i++)assert.equal(f.switchTo(i,{x:i+20,y:0,z:21}).x,i);assert.equal(f.switchTo(0,{x:44,y:3.6,z:-10}).x,21);assert.equal(f.switchTo(9,{x:0,y:0,z:0}),null);assert.equal(f.index,0);assert.equal(f.members[4].position.y,3.6);});
test('电梯每层均可呼梯并到达其他层，运行时不可重新选层',()=>{for(const from of FLOORS)for(const to of FLOORS){const lift=new Elevator();if(from===to){assert.equal(lift.request(from.y,to.y),false);continue;}assert.ok(lift.request(from.y,to.y));assert.equal(lift.request(from.y,0),false);let carried=false,arrived=false;for(let i=0;i<1800;i++){const event=lift.update(1/60);if(lift.passenger)carried=true;if(event==='arrived'){arrived=true;break;}}assert.ok(carried&&arrived);assert.equal(lift.y,to.y);assert.equal(lift.phase,'idle');assert.equal(lift.door,1);}});
test('电梯出口均可站立，井道禁止普通行走，楼板切口不覆盖轿厢',()=>{for(const f of FLOORS){assert.ok(canMove(LIFT.exitX,LIFT.z,f.y),String(f.y));assert.equal(canMove(LIFT.x,LIFT.z,f.y),false);}const parts=cutLiftFloor(-16,-6,10,26);for(const p of parts)assert.equal(shaftContains(p.x,p.z),false);const area=parts.reduce((s,p)=>s+p.w*p.d,0);assert.ok(Math.abs(area-(260-1.3*1.4))<1e-8);});
test('自行车沿平地移动，阻止冲楼梯和穿墙',()=>{const p={x:3,y:0,z:19};moveBicycle(p,2,0);assert.ok(p.x>4.9);const stair={x:9.75,y:0,z:-16};moveBicycle(stair,0,8);assert.equal(stair.y,0);assert.ok(stair.z<-14.5);const wall={x:0,y:0,z:-16};moveBicycle(wall,0,-10);assert.ok(wall.z>-18);});
test('天台电梯厅与天台主区之间的连桥可往返',()=>{const p={x:LIFT.exitX,y:7.2,z:LIFT.z};movePlayer(p,7,0);assert.ok(p.x>-10);movePlayer(p,LIFT.exitX-p.x,0);assert.ok(Math.abs(p.x-LIFT.exitX)<.1);});

test('电梯井各层有真实楼板开口，运行不穿过静态地板',()=>{const world=createWorld();world.root.updateMatrixWorld(true);const ray=new T.Raycaster(new T.Vector3(LIFT.x,10,LIFT.z),new T.Vector3(0,-1,0));const hits=ray.intersectObjects(world.merged.children,false);for(const f of FLOORS)assert.ok(!hits.some(hit=>Math.abs(hit.point.y-f.y)<.3),String(f.y));});

test('同层已开门时只关门一次，先上车再关门，到站开门后才下车',()=>{const lift=new Elevator();assert.ok(lift.request(0,3.6));assert.equal(lift.phase,'board');let closes=0,last=lift.phase,opened=false,exited=false;for(let i=0;i<1200;i++){const event=lift.update(1/60);if(lift.phase==='close'&&last!=='close'){closes++;assert.equal(lift.boarding,1);}if(lift.phase==='exit'){assert.equal(lift.door,1);opened=true;}if(event==='arrived'){exited=true;break;}last=lift.phase;}assert.equal(closes,1);assert.ok(opened&&exited);assert.equal(lift.exiting,1);});
