import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {AdaptiveQuality,PROFILES,lodForDistance,partitionPlaces} from './performance.mjs';
import {createVegetation} from './vegetation.mjs';
const report=JSON.parse(fs.readFileSync(new URL('../assets/runtime/lod-report.json',import.meta.url)));
function simulate(a,fps,seconds){const changes=[];for(let i=0;i<fps*seconds;i++){const changed=a.sample(1/fps);if(changed)changes.push(changed);}return changes;}
test('持续低帧率自动降级，恢复后等待足够时间再升级',()=>{const a=new AdaptiveQuality();assert.deepEqual(simulate(a,25,8),['flow']);assert.equal(a.level,0);assert.deepEqual(simulate(a,60,5),[]);assert.ok(simulate(a,60,26).includes('balanced'));});
test('手动选择的精细画质不会被自动模式覆盖',()=>{const a=new AdaptiveQuality();a.setMode('high');assert.deepEqual(simulate(a,20,20),[]);assert.equal(a.level,2);assert.equal(a.setMode('auto'),'balanced');});
test('标签页恢复或加载长停顿不引起误降档',()=>{const a=new AdaptiveQuality();a.sample(8);assert.deepEqual(simulate(a,60,3),[]);assert.equal(a.level,1);});
test('阈值附近的短暂帧率波动不反复切换画质',()=>{const a=new AdaptiveQuality();for(let i=0;i<12;i++){assert.deepEqual(simulate(a,35,1),[]);assert.deepEqual(simulate(a,45,1),[]);}assert.equal(a.level,1);});
test('流畅模式确实减少几何、阴影、像素量并禁用反射',()=>{assert.ok(PROFILES.flow.shadowSize<PROFILES.high.shadowSize);assert.ok(PROFILES.flow.pixelRatio<1);assert.equal(PROFILES.flow.reflectionInterval,Infinity);assert.equal(PROFILES.flow.ao,false);assert.equal(lodForDistance(35,PROFILES.flow),2);});
test('植被分区不会丢失或重复实例',()=>{const places=Array.from({length:43},(_,i)=>({x:Math.sin(i)*40,z:Math.cos(i)*40}));const grouped=partitionPlaces(places);assert.ok(grouped.length>8);assert.equal(grouped.flat().length,43);assert.equal(new Set(grouped.flat()).size,43);});
test('LOD 切换每个分区只显示一档，近处保留原网格',()=>{const scene=new T.Scene(),template=new T.Group();template.userData.height=1;const geo=new T.BoxGeometry(1,1,1);const reduced=Buffer.from(Uint32Array.from([0,1,2,0,2,3]).buffer).toString('base64');geo.userData.lod={medium:reduced,far:reduced};template.add(new T.Mesh(geo,new T.MeshBasicMaterial()));const vegetation=createVegetation(scene);vegetation.add(template,[{x:0,z:0,height:1},{x:40,z:0,height:1}]);const camera=new T.PerspectiveCamera();camera.position.set(0,1,2);vegetation.update(camera,PROFILES.balanced);assert.equal(scene.children.filter(g=>g.visible).length,2);assert.equal(vegetation.stats.nearCells,1);const nearCount=vegetation.stats.triangles;camera.position.set(100,50,100);vegetation.update(camera,PROFILES.balanced);assert.equal(vegetation.stats.nearCells,0);assert.ok(vegetation.stats.triangles<nearCount);});
test('远景树木面数低于原始的 8%，中景低于 25%',()=>{const tree=report.find(x=>x.id==='tree_small_02');assert.ok(tree.far/tree.near<.08);assert.ok(tree.medium/tree.near<.25);});
test('所有模型的 LOD 索引有效且不会增加面数',()=>{for(const entry of report){const b=fs.readFileSync(new URL('../assets/runtime/'+entry.id+'.glb',import.meta.url));const doc=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));for(const m of doc.meshes)for(const p of m.primitives){const max=doc.accessors[p.attributes.POSITION].count;for(const key of['medium','far']){const raw=Buffer.from(p.extras.lod[key],'base64');const indices=new Uint32Array(Uint8Array.from(raw).buffer);assert.ok(indices.length>0);assert.equal(indices.length%3,0);assert.ok(indices.length<=doc.accessors[p.indices].count);assert.ok(indices.every(i=>i<max));}}}});
